# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_auto_20170829_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='location',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
